import pandas as pd
import numpy as np
import pytest
import sys
from pathlib import Path

# Add python ml directory to path
sys.path.insert(0, str(Path(__file__).parent.parent.parent / "python" / "ml"))
from train_model import engineer_features

def test_engineer_features():
    """
    Test that the feature engineering function correctly creates:
    - lag_1, lag_7, lag_14
    - rolling_mean_7d, rolling_std_7d
    And correctly drops the NaN rows generated by shifts.
    """
    # Create 30 days of synthetic data
    dates = pd.date_range("2023-01-01", periods=30, freq="D")
    revenue = np.linspace(100, 390, 30) # 100, 110, 120...
    
    raw_df = pd.DataFrame({"daily_revenue": revenue}, index=dates)
    
    # Run the feature engineering
    processed_df = engineer_features(raw_df)
    
    # 1. Check shape: since max lag is 14, first 14 rows should be dropped
    # Wait, rolling_std_7d is on shift(1). So it needs 7 days *before* the current day.
    # So day 8 has shift(1) = day 7, rolling window = days 1-7.
    # Lag 14 needs 14 days before current day. So day 15 has lag 14 = day 1.
    # Therefore, row 15 (index 14) is the first valid row.
    # 30 total rows - 14 dropped rows = 16 rows remaining.
    assert len(processed_df) == 16
    
    # 2. Check lag 1 logic
    # First valid row in processed_df corresponds to 2023-01-15 (15th day)
    # daily_revenue for 15th day = 100 + 14*10 = 240
    # lag 1 should be 14th day = 230
    assert processed_df.iloc[0]["lag_1"] == 230.0
    
    # 3. Check lag 7 logic
    # lag 7 should be 8th day = 170
    assert processed_df.iloc[0]["lag_7"] == 170.0
    
    # 4. Check lag 14 logic
    # lag 14 should be 1st day = 100
    assert processed_df.iloc[0]["lag_14"] == 100.0
    
    # 5. Check rolling mean logic
    # rolling mean of days 8-14
    # (170+180+190+200+210+220+230) / 7 = 1400 / 7 = 200
    assert processed_df.iloc[0]["rolling_mean_7d"] == 200.0
